name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    env:
      APP_URL: steps.deployment.outputs.page_url
      VITE_BUILD_DT: $(date '+%Y-%m-%d %H:%M:%S CET')
      VITE_BUILD_ID: ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT}-${GITHUB_SHA:0:7}


    steps:
      # - name: Set environment variable
      #   run: | 
      #     # echo "TZ='Europe/Warsaw'" >> $GITHUB_ENV
      #     echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV
      #     echo "VITE_BUILD_DT=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
      #     echo "VITE_BUILD_ID=${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT}-${GITHUB_SHA:0:7}" >> $GITHUB_ENV


      # - name: Use environment variable
      #   run: |
      #     echo "Deploying at $BUILD_TIME"
      #     echo "The value of VITE_BUILD_DT is $VITE_BUILD_DT"
      #     echo "The value of VITE_BUILD_ID is $VITE_BUILD_ID"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci
                  
      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # - name: Sprawdzam
      #   run: |
      #     env
      #     pwd
      #     ls -lah ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        
      # - name: Sprawdzam
      #   run: |
      #     # env
      #     pwd
      #     ls -lah

      - name: Notify ntfy
        if: success()
        env:
          NTFY_TOKEN: ${{ secrets.NTFY_TOKEN }}
          NTFY_TOPIC: ${{ vars.NTFY_TOPIC }}
        run: |
          echo "AAAAAAAAAA ${{ steps.deployment.outputs.page_url }} AAAAAAAAAAAAA"; pwd; ls -lah;